### ISSUE TITLE
Why @objc?

### ISSUE THREAD

**Issue by dcvz** [getsentry/sentry-swift#15]
Hey guys, I'm currently working on a PR to fix some issues I was having with this new library. One thing I'd like to know is why there's such a spread use of @objc tags. As I don't see any inter-operability with Objective-C code.

**Comment by joshdholtz** [comment]
@dcvz Thanks for the question! The '@objc' is needed to make methods available to use in Objective-C. You can see how to use the library in Objective-C here - https://github.com/getsentry/sentry-swift/blob/master/Examples/ObjCExample/ObjCExample/ViewController.m. Without the `@objc`, a lot of those classes/methods would not be able to be called from Objective-C.

If you believe there is another way to get this done, please let me know 😊  I was not a _huge_ fan of putting in all the @objc but this Swift client is intended to be used in both Swift and Objective-C environments so that only one codebase needs to be maintained.

**Comment by dcvz** [comment]
I saw that there was also a new `sentry-objc` client. Is the goal that they both support both platforms? It seems a bit redundant.

**Comment by joshdholtz** [comment]
@dcvz The `sentry-objc` client was made for some systems that only work with iOS 6 still (which Swift does not work with)

**Comment by dcvz** [comment]
Ah, got it! Thanks for the info :)
