### ISSUE TITLE
SSLHandshakeFailed

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry-swift#60]
Hey guys!  I just upgraded our app to use SentrySwift and we started seeing a bunch of SSLHandshakeFailed errors in the logs.  Turns out, there's some issue with the SSL cert on the old `app.sentry.com` hostname....switching to the new `sentry.io` hostname fixed the issue.  Mostly just posting this so if anybody else is running into this, they'll find this solution when Googling.  (And if you guys can figure out what the SSL issue is, that'd be rad too.  I couldn't)

**Comment by mattrobenolt** [comment]
Hey @edenman, can you provide anymore information? Both of these hostnames use the same SSL certificate and are served from the same IP addresses. If anything, `app.getsentry.com` in theory should be more accessible since it's the primary domain on the cert whereas `sentry.io` is on the SAN.

I'm happy to help and provide anymore information, but we haven't had this issue before with anything else that I'm aware of.

**Comment by mattrobenolt** [comment]
Wait, I just reread. Do you mean `app.sentry.com` or `app.getsentry.com`? `app.sentry.com` wouldn't be us. If that's the case, that'd be one explanation. :)

**Comment by edenman** [comment]
Oops.  Meant `app.getsentry.com`.

And it turns out the SSL errors may not have been fixed by switching hostnames.  Sorry for the noise, might not even be related to you guys. I thought I had isolated a pattern but it seems like they're still happening after I made the hostname switch.
