### ISSUE TITLE
The request timed out - Too many requests

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry-swift#98]
```
SentrySwift - Error:: error = Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x6000004424c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://sentry.io/api/71464/store/, NSErrorFailingURLKey=https://sentry.io/api/71464/store/, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}
```
@edenman

**Comment by HazAT** [comment]
@edenman 
Please update to `1.3.3` this will fix your problem.

**Comment by edenman** [comment]
Cool.  Now I just have thousands of 
```
SentrySwift - Error:: Rate limit reached, event will be stored and sent later
```
messages in the logs.

**Comment by edenman** [comment]
I added some logging to `RequestManager` to keep track of how many request had been kicked off and how many got a 429:

```
2016-12-22 21:16:41.897 recharge-consumer-ios[2595:4034301] ERICSENTRY Of 151 we have 131 429 responses
```

**Comment by edenman** [comment]
(feel free to tell me if the answer is just "turn down your logging, dude" but at least with Raven, captureMessage was pretty lightweight, that's why we've hooked it up to our warning+error log messages with Corvus)

**Comment by mitsuhiko** [comment]
@edenman essentially the issue here is that the quota is a per minute quota at the time of event submission. Because you had 151 pending messages and it tried to send them in one go it immediately ran against that quota.

Normally you should not have 151 events that are sent in one go. I assume this is because it failed to submit in the past so it kept them around.

**Comment by edenman** [comment]
@mitsuhiko this was on a fresh install of the app.

**Comment by mitsuhiko** [comment]
@edenman it still tried to send out 151 events in one go. That's pretty massive. I wonder what would have caused this.

**Comment by edenman** [comment]
@mitsuhiko I started the app, and I logged a bunch of warning messages during start up.  Those were all converted to `captureMessage` calls, and SentrySwift apparently tried to send them in huge batches (more than what the server allows).  Should I open a new issue for this, or would you prefer to re-open this one?

**Comment by HazAT** [comment]
@edenman There is no issue with the client anymore, the current issue you have is that your sentry account does not allow sending so many requests at once.
You if you always send that many events consider reducing them on the client or upgrading your account to allow sending more.

**Comment by edenman** [comment]
sorry, i realize that's probably not a polite response, and you guys are doing the best you can.  A few things:

- the previous client (Raven) allowed logging that many events with no problem.  it's hard to justify upgrading if our log messages can suddenly fail if we call the API too many times.
- why does the sentry-swift client try to send all the events at once, if it knows they won't be accepted by the server?  i thought the whole point of #99 was to batch the requests and avoid overloading the server?

**Comment by mitsuhiko** [comment]
@edenman the question here is why so many things are queued up for delivery. I would be curious to see if there is a common case we are missing. The reason we're not super concerned about this that the new pricing model is intended to support this model a lot better than the old 60 seconds buckets.

**Comment by edenman** [comment]
@mitsuhiko like i said: I'm calling captureMessage a bunch of times (every time i log a warning or an error, which happens quite a bit on app start).  is that not a supported usecase?

if i switch to the new pricing model, will i stop getting the 429 errors?

**Comment by mitsuhiko** [comment]
@edenman that's a perfectly supported use case. However typically `captureMessage` will send right away as the event happens not just on restart which is where you would currently hit the request limits the most. So the question is why there would be a lot of those events being sent on startup. Theoretically that should only happen for the crash event or if the device did not have network connectivity when you called `captureMessage`.

> if i switch to the new pricing model, will i stop getting the 429 errors?

The idea of the new pricing model is that we no longer have arbitrary buckets but you define yourself how many events you want to pay for. You can find some information here: https://blog.sentry.io/2017/01/05/a-new-pricing-model.html

**Comment by edenman** [comment]
@mitsuhiko Again: this is not a "queued up events being sent on restart" issue.  I see 429s even on a clean install.  There are lots of messages being sent because I'm calling `captureMessage` lots of times.

Does the SentrySwift client have a concept of how many events are allowed to be sent to the server in a given time window?  In the new pricing model or old?

**Comment by mitsuhiko** [comment]
@edenman if this is happening not on restart then you are simply sending more events than the rate limit of your plan is. That is intended behavior. On the old plans it's a rate limit per minute and new plans it will be a rate limit per hour and you can more dynamically scale what you want to accept with the more flexible pricing.

SentrySwift is not aware of the rate limiting on the server and will not gain that knowledge. If you are over your limit you are over the limit and no retransmission will be attempted later. This is intentional because otherwise you will just take your own project down with ancient events.
